name = "FlowOverCircle"
uuid = "1fc04e5d-1dd1-42ff-8d75-1d53504b2476"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
GeometricFlux = "7e08b658-56d3-11e9-2997-919d5b31e4ea"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NeuralOperators = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
WaterLily = "ed894a53-35f9-47f1-b17f-85db9237eebd"

[compat]
BSON = "0.3"
CUDA = "3.12, 4, 5"
Flux = "0.13"
FluxTraining = "0.3"
GeometricFlux = "0.13"
Graphs = "1.7"
MLUtils = "0.3"
NeuralOperators = "0.4"
Plots = "1.36"
Pluto = "0.19"
ProgressMeter = "1.7"
WaterLily = "0.2, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
