name = "DoublePendulum"
uuid = "0c23c1c1-5f41-4617-a685-ac46aae913c3"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NeuralOperators = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
BSON = "0.3"
CSV = "0.10"
CUDA = "3.12, 4, 5"
DataDeps = "0.7"
DataFrames = "1.4"
Flux = "0.13"
FluxTraining = "0.3"
MLUtils = "0.3, 0.4"
NeuralOperators = "0.4"
Plots = "1.36"
Pluto = "0.19"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
