name = "NeuralOperators"
uuid = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.4.7"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GeometricFlux = "7e08b658-56d3-11e9-2997-919d5b31e4ea"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Aqua = "0.8"
CUDA = "3.5, 4, 5"
ChainRulesCore = "1.15"
FFTW = "1.3.0"
Flux = "0.13.4"
GeometricFlux = "0.13.5"
Graphs = "1.6"
SafeTestsets = "0.1"
Statistics = "1.10"
Test = "1"
Tullio = "0.3"
Zygote = "0.6.61"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Graphs", "SafeTestsets", "Test"]
