name = "NeuralOperators"
uuid = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"
authors = ["Avik Pal <avikpal@mit.edu>"]
version = "1.0.0-DEV"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
LuxLib = "82251201-b29d-42c6-8e01-566dec8acb11"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
WeightInitializers = "d49dbf32-c5c2-4618-8acc-27bb2598ef2d"

[compat]
ArgCheck = "2.3.0"
ChainRulesCore = "1.24.0"
ConcreteStructs = "0.2.3"
FFTW = "1.8.0"
Lux = "0.5.64"
LuxCore = "0.1.24"
LuxLib = "0.3.42"
NNlib = "0.9.21"
Random = "1.10"
WeightInitializers = "1"
julia = "1.10"
