name = "NeuralOperators"
uuid = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Fetch = "bb354801-46f6-40b6-9c3d-d42d7a74c775"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
CUDA = "3.3"
CUDAKernels = "0.3"
DataDeps = "0.7"
FFTW = "1.4"
Fetch = "0.1"
Flux = "0.12"
KernelAbstractions = "0.7"
MAT = "0.10"
StatsBase = "0.33"
Tullio = "0.3"
Zygote = "0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
