name = "Burgers"
uuid = "5b053d85-f964-4905-ae31-99551cd8d3ad"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NeuralOperators = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"

[compat]
BSON = "0.3"
CUDA = "3.12, 4, 5"
DataDeps = "0.7"
Flux = "0.13"
FluxTraining = "0.3"
MAT = "0.10"
MLUtils = "0.3, 0.4"
NeuralOperators = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
